version: '3.8'

services:
  postgres:
    container_name: postgresql
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tech-talks
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: cache-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data