version: '3.8'

services:
  postgres:
    container_name: tech-talks-nest-api
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tech-talks
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres